name: Security Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PowerShell Modules
      run: |
        pwsh -Command "Install-Module Az -Force -Scope CurrentUser"
        pwsh -Command "Install-Module Microsoft.Graph -Force -Scope CurrentUser"

    - name: Run PowerShell and Python Scripts
      run: |
        pwsh ./EntraID/ConditionalAccessAudit.ps1
        pwsh ./AzureSecurity/DefenderRecommendationsExport.ps1
        python ./ThreatModeling/stride_threat_model.py
        pwsh ./Alerting/SentinelToTeams.ps1
